### Numpy Library
- processesing N-Dimensional array


In [11]:
import numpy as np
li=[1,2,3,'z']
b=np.array(li)
c=np.arange(15)
c


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
rn=np.random.randint(1,100,size=10)
rn

array([89, 47, 27, 77, 88, 84, 38, 97, 39, 22])

In [115]:
n3=np.random.randint(0,2,size=(3,3,3,3))

n3[2][2][2][2]

1

In [123]:
n3.ndim
n3.size
n3.shape
n3.dtype
n3.itemsize
n3.nbytes

324

In [127]:
m=np.ones((3,3))
m

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Pandas

Use Cases


Data Cleaning
Data Transformation
Data Analysis
Notations


Series

DataFrames

In [2]:
list1={"name":"pavan","idno":"n140934"}
list2={"name":"kumar","idno":"n140935"}
import pandas as pd
list1=pd.Series(list1)
list2={"Name":list1,"IdNO":list2}
db=pd.DataFrame(list2)
db
db["Name"]
db

Name     IdNO
idno  n140934  n140935
name    pavan    kumar